FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=torus/torus
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY torus.tar.gz /torus.tar.gz
RUN tar -xvf /torus.tar.gz

#ADD . /torus
RUN cd /torus/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /torus && scripts/windows-crosscompile/compile-torus.sh
